### ISSUE TITLE
Failed to require extension

### ISSUE THREAD

**Issue by samuelthan** [sensu-extensions/sensu-extensions-system-profile-wmi#5]
OS: Ubuntu 16.04
Sensu Version: 1.1.1

I've installed the sensu extensions system profile using the following method:
$ sensu-install -e sensu-extensions-system-profile-wmi

Created a json file in /etc/sensu/conf.d/extensions.json  with the following content:
{
  "extensions": {
    "system-profile-wmi": {
      "gem": "sensu-extensions-system-profile-wmi"
    }
  }
}

After restarted sensu server and client. 
I got this error when tailing the log files 

"failed to require extension","gem":"sensu-extensions-system-profile-wmi","version":null,"error":{"path":"win32ole","~bt_locations":"#<Thread::Backtrace:0x00000001c248d0>","~cause":{"path":"sensu/extensions/system-profile-wmi","~bt_locations":"#<Thread::Backtrace:0x00000001d5a8a8>","~cause":null,"~mesg":"cannot load such file -- sensu/extensions/system-profile-wmi","~bt":["/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:117:in `load_gem'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:30:in `block in load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:28:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:28:in `load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:44:in `get'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/daemon.rb:158:in `load_extensions'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/daemon.rb:58:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/client/process.rb:30:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/client/process.rb:18:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/client/process.rb:18:in `run'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/exe/sensu-client:10:in `<top (required)>'","/opt/sensu/bin/sensu-client:22:in `load'","/opt/sensu/bin/sensu-client:22:in `<main>'"]},"~mesg":"cannot load such file -- win32ole","~bt":["/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-system-profile-wmi-1.0.0/lib/sensu/extensions/system-profile-wmi.rb:27:in `<top (required)>'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'","/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions/loader.rb:117:in `load_gem'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:30:in `block in load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:28:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:28:in `load'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-extensions-1.9.0/lib/sensu/extensions.rb:44:in `get'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/daemon.rb:158:in `load_extensions'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/daemon.rb:58:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/client/process.rb:30:in `initialize'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/client/process.rb:18:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/lib/sensu/client/process.rb:18:in `run'","/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-1.1.1/exe/sensu-client:10:in `<top (required)>'","/opt/sensu/bin/sensu-client:22:in `load'","/opt/sensu/bin/sensu-client:22:in `<main>'"]}}
{"timestamp":"2017-10-30T16:22:20.051731+1100","level":"warn","message":"ignoring extension","gem":"sensu-extensions-system-profile-wmi"}

**Comment by cwjohnston** [comment]
Hi @samuelthan, looks like you are trying to load this extension on a Linux system. This extension works only under sensu-client running on Windows platform. Perhaps you should try https://github.com/sensu-extensions/sensu-extensions-system-profile

**Comment by samuelthan** [comment]
oh .. oopss.. sorry bout that, didn't know it didn't support linux. Will give that a try then.
